setting:
  name: "test_replica_gs"
  output_root: "./experiments"
  pc_path: "./data/Replica/room0/rgbd_ply"
  pose_path: "./data/Replica/room0/poses.txt"
  color_channel: 3
  color_map_on: True 
  first_frame_ref: False
process:
  min_range_m: 0.05
  max_range_m: 10.0
  min_z_m: -10.0
  vox_down_m: 0.01
sampler:
  surface_sample_range_m: 0.04
  surface_sample_n: 2
  free_sample_begin_ratio: 0.6
  free_sample_end_dist_m: 0.1
  free_front_sample_n: 1
  free_behind_sample_n: 1
neuralpoints:
  voxel_size_m: 0.05 # 0.04
  query_nn_k: 6
  feature_dim: 32
  color_feature_dim: 16
decoder:
  freeze_after_frame: 40
gs:
  dist_concat_on: False
  view_concat_on: False
  gs_iters: 20
  gaussian_bs_ratio: 2.0
  gs_keyframe_interval: 4
  img_pool_size: 40
  gs_down_rate: 1
  gs_vis_down_rate: 1
  inverse_depth_loss: False
  lambda_depth: 10.0 # 10.0
  lambda_normal_depth: 0.1
  # lambda_isotropic: 100.0
  lambda_area: 1e-4 # 1e-3
  lambda_opacity: 1e-3
  lambda_sdf_cons: 0.5
  lambda_sdf_normal_cons: 0.5 # rendered normal seems to be better without this loss # 0.1
  lambda_sdf: 0.5
loss:
  sigma_sigmoid_m: 0.015
  ekional_loss_on: True
  weight_e: 1.0
  numerical_grad_on: True
decoder:
  freeze_after_frame: 40
continual:
  batch_size_new_sample: 2000
  pool_capacity: 2e7
  pool_filter_freq: 10
tracker:
  # photo_loss: True
  # photo_weight: 0.01
  eigenvalue_check: False
  source_vox_down_m: 0.05
  iter_n: 50
  min_grad_norm: 0.4
  max_grad_norm: 2.5
  GM_grad: 0.3
  GM_dist: 0.05
  term_deg: 1e-3
  term_m: 1e-4
optimizer:
  iters: 15 # you need more iterations for achieveing a nice mesh # 50
  batch_size: 8192
  # ba_freq_frame: 0
  # lr_pose_ba: 1e-3
eval:
  o3d_vis_on: True
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 12
  sensor_cad_path: ./cad/camera.ply
  skip_top_voxel: 3