setting: 
  name: "test_waymo_gs"
  output_root: "./experiments"
  deskew: False
  color_channel: 3
  color_map_on: True # pin slam does not make use of color
process:
  min_range_m: 1.0
  max_range_m: 80.0 # 80.0
  vox_down_m: 0.08
  dynamic_filter_on: True
  dynamic_sdf_ratio_thre: 0.5
  dynamic_certainty_thre: 1.0
  dynamic_min_grad_norm_thre: 0.3
sampler:
  surface_sample_range_m: 0.25
  surface_sample_n: 3
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 3
neuralpoints:
  voxel_size_m: 0.3
  search_alpha: 0.8
gs:
  monodepth_on: True # True
  gs_iters: 50 # 100 has good results
  n_gaussian: 8
  gaussian_bs_ratio: 1.0
  gs_keyframe_interval: 2 # 2
  img_pool_size: 50 # 15
  img_test_pool_size: 0
  gs_down_rate: 1
  gs_vis_down_rate: 1
  inverse_depth_loss: True
  lambda_depth: 10.0 # 10.0
  # lambda_normal_depth: 0.05
  # lambda_normal_smooth: 0.1
  lambda_mono_normal: 0.01
  # lambda_isotropic: 1.0
  # lambda_area: 1e-2 # 1e-3
  lambda_opacity: 1e-4 # 5e-4 # 1e-3 # 5e-4 # increase to have more valid gaussians
  # lambda_sky: 0.01 # not much impact, should not be too large
  lambda_sdf_cons: 0.1
  lambda_sdf_normal_cons: 0.1 # rendered normal seems to be better without this loss # 0.1
  lambda_sdf: 0.1
continual:
  batch_size_new_sample: 1000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  source_vox_down_m: 0.6
  iter_n: 50
  term_deg: 0.1
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 10
  local_loop_dist_thre: 15.0
optimizer: # mappers 
  batch_size: 8196
  adaptive_iters: True
eval:
  mesh_freq_frame: 5 # reconstruct the mesh every x frames
  mesh_min_nn: 15