setting: 
  name: "test_kitti360_gs"
  output_root: "./experiments"
  deskew: True
  kitti_correct: True
  correct_deg: 0.195
  color_channel: 3
  color_map_on: True
process:
  max_range_m: 80.0 # 80.0
  vox_down_m: 0.08
  estimate_normal: True
sampler:
  surface_sample_range_m: 0.25 
neuralpoints:
  voxel_size_m: 0.25 # 0.5
  search_alpha: 0.5
gs:
  gs_iters: 10
  gs_bs: 2
  gs_keyframe_interval: 2
  img_pool_size: 15
  gs_down_rate: 0
  gs_vis_down_rate: 0
  sh_degree: 1
  lambda_sdf: 1.0
  lambda_sdf_normal: 0.5
continual:
  batch_size_new_sample: 2000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  source_vox_down_m: 0.8
  iter_n: 50
  term_deg: 0.1
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 10
  local_loop_dist_thre: 15.0
optimizer: # mappers 
  batch_size: 16384
  adaptive_iters: True
eval:
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 9
  sensor_cad_path: ./cad/kitti_car.ply