setting: 
  name: "test_kitti360_gs"
  output_root: "./experiments"
  deskew: False
  kitti_correct: True
  correct_deg: 0.195
  color_channel: 3
  color_map_on: True 
process:
  max_range_m: 80.0 # 80.0
  min_range_m: 3.0
  min_z_m: -3.5
  vox_down_m: 0.05
  estimate_normal: False
  # dynamic_filter_on: True
  # dynamic_certainty_thre: 1.0
  # dynamic_sdf_ratio_thre: 0.5
  # dynamic_min_grad_norm_thre: 0.25
sampler:
  surface_sample_range_m: 0.2 
  surface_sample_n: 4
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 4
neuralpoints:
  voxel_size_m: 0.25 # smaller value does not neccessarily lead to a better result here
  search_alpha: 0.8
  query_nn_k: 8
  feature_dim: 32
  color_feature_dim: 16
loss:
  sigma_sigmoid_m: 0.08
  loss_weight_on: True
  dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
gs:
  monodepth_on: True # True
  exposure_correction_on: False
  gs_iters: 50 # 100 has good results
  n_gaussian: 8
  gaussian_bs_ratio: 1.0
  gs_keyframe_interval: 2 # 2
  img_pool_size: 15 # 15

  img_test_pool_size: 0
  gs_down_rate: 0
  gs_vis_down_rate: 0
  # lambda_ssim: 0.0
  inverse_depth_loss: True
  lambda_depth: 10.0 # 10.0
  # lambda_normal_depth: 0.05
  # lambda_normal_smooth: 0.1
  # lambda_distort: 0.0
  lambda_mono_normal: 0.01
  # lambda_isotropic: 1.0
  # lambda_area: 1e-2 # 1e-3
  lambda_opacity: 5e-4 # 5e-4 # 1e-3 # 5e-4 # increase to have more valid gaussians
  # lambda_sky: 1e-3
  lambda_sdf_cons: 0.1
  lambda_sdf_normal_cons: 0.1 # rendered normal seems to be better without this loss # 0.1
  lambda_sdf: 0.2
continual:
  batch_size_new_sample: 2000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  photo_loss: False
  source_vox_down_m: 0.6
  iter_n: 50
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 10
  local_loop_dist_thre: 15.0
optimizer: # mappers 
  batch_size: 16384
  iters: 10
eval:
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 12
  eval_on: False
  sensor_cad_path: ./cad/kitti_car.ply