setting:
  name: "test_ipbcar_gs"
  output_root: "./experiments"
  deskew: True
  color_channel: 3
  color_map_on: True # pin slam does not make use of color
process:
  min_range_m: 3.0
  max_range_m: 80.0
  estimate_normal: True
sampler:
  surface_sample_range_m: 0.3 
neuralpoints:
  voxel_size_m: 0.4
  search_alpha: 0.5
continual:
  batch_size_new_sample: 1000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  source_vox_down_m: 1.2
  term_deg: 0.1
  iter_n: 50
pgo:
  map_context: True
  pgo_freq_frame: 30
  virtual_side_count: 6
gs:
  gs_iters: 5
  gs_bs: 5
  gs_keyframe_interval: 1
  img_pool_size: 30
  gs_down_rate: 3
  gs_vis_down_rate: 2
  sh_degree: 1
  movable_gs: False
optimizer: # mapper
  iters: 15  # iterations per frame
  batch_size: 8000
eval:
  sensor_cad_path: ./cad/ipb_car.ply
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 15