setting: 
  name: "test_kitti_gs"
  output_root: "./experiments"
  color_channel: 3
  deskew: False
  kitti_correct: True
  correct_deg: 0.195
  color_map_on: False # pin slam does not make use of color
process:
  max_range_m: 60.0 # 80.0
  vox_down_m: 0.08
  estimate_normal: True
sampler:
  surface_sample_range_m: 0.3 
neuralpoints:
  voxel_size_m: 0.3 # 0.5
gs:
  gs_iters: 5
  gs_bs: 5
  gs_keyframe_interval: 5
  img_pool_size: 10
  sh_degree: 1
continual:
  batch_size_new_sample: 1000
  pool_capacity: 1e7
  pool_filter_freq: 10
tracker:
  source_vox_down_m: 1.2
  iter_n: 20
  term_deg: 0.1
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 10
  local_loop_dist_thre: 15.0
optimizer: # mappers 
  batch_size: 4000
  adaptive_iters: True
eval:
  mesh_freq_frame: 50 # reconstruct the mesh every x frames
  mesh_min_nn: 9
  sensor_cad_path: ./cad/kitti_car.ply