setting:
  name: "test_ipbcar_gs"
  output_root: "./experiments"
  deskew: True
  color_channel: 3
  color_map_on: True
process:
  min_range_m: 2.5
  max_range_m: 60.0
  vox_down_m: 0.08
  estimate_normal: False
sampler:
  surface_sample_range_m: 0.3
  surface_sample_n: 2
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  voxel_size_m: 0.3
  search_alpha: 0.8
  query_nn_k: 8
  feature_dim: 32
  color_feature_dim: 16 # 
decoder:
  freeze_after_frame: 40
continual:
  batch_size_new_sample: 1500
  pool_capacity: 1e7 # this is often the part taken a lot of memory
tracker:
  source_vox_down_m: 0.6
  iter_n: 50
pgo:
  map_context: True
  pgo_freq_frame: 30
  virtual_side_count: 6
gs:
  monodepth_on: False
  exposure_correction_on: False
  view_concat_on: True
  gs_iters: 50 # 50
  gaussian_bs_ratio: 4.0
  gs_keyframe_interval: 2
  img_pool_size: 30 # TODO
  gs_down_rate: 1
  gs_vis_down_rate: 1
  inverse_depth_loss: True
  lambda_depth: 10.0
  lambda_opacity: 5e-3 # 1e-3 # increase to have more valid gaussians
  lambda_area: 1e-3 # 1e-3
  lambda_mono_normal: 0.01
  lambda_sdf_cons: 0.2
  lambda_sdf_normal_cons: 0.2 # rendered normal seems to be better without this loss
  lambda_sdf: 1.0 # 0.1 # what should this value be like
optimizer: # mapper
  iters: 15  # iterations per frame
  batch_size: 8192
eval:
  o3d_vis_on: False # if false, mesh vis is also disabled
  sensor_cad_path: ./cad/ipb_car_cheap.ply
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 20