setting: 
  name: "test_kitti_mot_gs"
  output_root: "./experiments"
  deskew: True
  kitti_correct: True
  correct_deg: 0.195
  color_channel: 3
  color_map_on: True 
process:
  max_range_m: 80.0 # 80.0
  vox_down_m: 0.05
  estimate_normal: False
sampler:
  surface_sample_range_m: 0.15 
  surface_sample_n: 5
  free_sample_begin_ratio: 0.3
  free_sample_end_dist_m: 1.0
  free_front_sample_n: 2
neuralpoints:
  voxel_size_m: 0.25
  search_alpha: 0.8
  query_nn_k: 8
loss:
  sigma_sigmoid_m: 0.08
  # loss_weight_on: True
  # dist_weight_scale: 0.8
  ekional_loss_on: True
  weight_e: 0.5
# gs:
#   monodepth_on: True
#   gs_iters: 10 # 10
#   gs_bs: 5
#   gaussian_bs: 16384
#   gs_keyframe_interval: 2
#   img_pool_size: 15 # 15
#   img_test_pool_size: 15
#   gs_down_rate: 0
#   gs_vis_down_rate: 0
#   sh_degree: 0 # According to experiments, it seems to not play an important role, but why
#   lambda_depth: 10.0 # 10.0
#   lambda_distort: 100.0
#   lambda_normal: 0.05 # not too big 0.05 
#   lambda_isotropic: 1.0 # todo
#   # lambda_sky: 0.01 # not much impact
#   # lambda_sdf_cons: 0.0
#   # lambda_sdf_normal_cons: 0.0
#   # lambda_sdf: 0.0
#   # actually making the results worse
#   lambda_sdf_cons: 0.0
#   lambda_sdf_normal_cons: 0.0 # rendered normal seems to be better without this loss
#   lambda_sdf: 0.0
continual:
  batch_size_new_sample: 3000
  pool_capacity: 1e7
  pool_filter_freq: 10
# tracker:
#   photo_loss: False
#   source_vox_down_m: 0.6
#   iter_n: 50
pgo:
  map_context: True
  pgo_freq_frame: 30
  context_cosdist: 0.3
  virtual_side_count: 10
  local_loop_dist_thre: 15.0
optimizer: # mappers 
  batch_size: 16384
  iters: 15 # i don't know how # TODO
eval:
  mesh_freq_frame: 10 # reconstruct the mesh every x frames
  mesh_min_nn: 12
  sensor_cad_path: ./cad/kitti_car.ply